Docstring fix
alexandrainst/alexandra-ml-template pull request #10
Opened 2024-03-06 09:46 UTC by bourdeet

When deploying a new project and running `make install` , I encounter two errors.

Example setup command:

```
cookiecutter -f gh:alexandrainst/alexandra-ml-template
```
Example configuration from the prompt:

```
You've downloaded /home/bourdeet/.cookiecutters/alexandra-ml-template before. Is it okay to delete and re-download it? [yes]: yes
project_name [Project name, in snake_case]: test_project
project_description [Short description of the project]: Here is my description
author_name [Your full name]: Test
email [<name>@alexandra.dk]: test@alexandra.dk
open_source [Is this a public open source project? [y/N]]: N
python_version [Your Python version, written as 3.xx]: 3.11
dependency_manager [Which dependency manager do you use? [pip/POETRY]]: pip
license_checker [Do you want to check that your dependencies are only using open source licenses? [Y/n]]: n
```

First error upon running `make install`:

```
Installing the 'test_project' project...
Initialized empty Git repository in /home/bourdeet/projects/RK_iot_forretningsdesign/tes/test_project/.git/
Signed with GPG key [ID GPG_KEY].
pre-commit installed at .git/hooks/pre-commit
Updated dependencies in pyproject.toml.
No .pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`
make[1]: *** [makefile:111: add-repo-to-git] Error 1
make: *** [makefile:36: install] Error 2
```

The first error can be avoided by adding a dot to the name `pre-commit-config.yaml`. When running make install again, I get a second error related to docstring formatting of some of the template files:

```
Installing the 'test_project' project...
[...]
pre-commit installed at .git/hooks/pre-commit
Updated dependencies in pyproject.toml.
black....................................................................Passed
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1
- files were modified by this hook

config/__init__.py:1:1: D104 Missing docstring in public package
src/scripts/freeze_dependencies.py:12:9: D102 Missing docstring in public method
src/scripts/freeze_dependencies.py:22:9: D102 Missing docstring in public method
tests/__init__.py:1:1: D104 Missing docstring in public package
tests/test_dummy.py:4:5: D103 Missing docstring in public function
Found 7 errors (2 fixed, 5 remaining).

nbstripout...........................................(no files to check)Skipped
mypy.....................................................................Passed
make[1]: *** [makefile:111: add-repo-to-git] Error 1
make: *** [makefile:36: install] Error 2
```

I have added the missing docstring in the problematic file.

2024-03-06 12:34 UTC, saattrupdan requested changes
Thanks for your contribution! I've got a few suggested changes, mostly related to the content of the docstrings.

2024-03-06 12:34 UTC, saattrupdan commented on {{cookiecutter.project_name}}/src/scripts/{{'' if cookiecutter.dependency_manager != 'pip' else 'freeze_dependencies.py'}}
> +        """Docstring to shut up ruff."""
Let's make this slightly more informative 🙃 

```suggestion
    def dump_list(self, v: list) -> str:
        """Convert a list object to a string representation on multiple lines.
        
        Args:
            v:
                The list to be dumped.
                
        Returns:
            A string representation of the list
        """
```

2024-03-06 12:34 UTC, saattrupdan commented on {{cookiecutter.project_name}}/src/scripts/{{'' if cookiecutter.dependency_manager != 'pip' else 'freeze_dependencies.py'}}
> +        """Docstring to shut up ruff."""
Let's make this slightly more informative 🙃 

```suggestion
    def dump_value(self, v) -> str:
        """Convert an object to a string representation.
        
        In case the object is a string then we ensure that newlines are preserved.
        
        Args:
            v:
                The object to be dumped.
                
        Returns:
            A string representation of the object.
        """"
```

2024-03-06 12:34 UTC, saattrupdan commented on {{cookiecutter.project_name}}/tests/__init__.py
> +"""Shutting up pylint comlaining about D104."""
Let's make this slightly more informative 🙃 

```suggestion
"""Unit tests for the project."""
```

2024-03-06 12:34 UTC, saattrupdan commented on {{cookiecutter.project_name}}/tests/test_dummy.py
> +    """Dummy Test module."""
```suggestion
    """Dummy test function."""
```

2024-03-07 13:21 UTC, bourdeet commented on {{cookiecutter.project_name}}/src/scripts/{{'' if cookiecutter.dependency_manager != 'pip' else 'freeze_dependencies.py'}}
> +        """Docstring to shut up ruff."""
agreed! I was actually in doubt about what that function did :p

2024-03-07 13:29 UTC, bourdeet commented
I am trying to check that the install runs fine, but I realized that calling:

```
cookiecutter -f git@github.com:alexandrainst/alexandra-ml-template
```

This downloads the template from the main branch. @saattrupdan  do you know if one can call a specific git branch from cookiecutter? I tried:

`cookiecutter -f gh:alexandrainst/alexandra-ml-template@docstring_fix`

`cookiecutter -f git@github.com:alexandrainst/alexandra-ml-template@docstring_fix`

`cookiecutter -f gh:alexandrainst/alexandra-ml-template.git@docstring_fix`

but it doesn't seem to work

2024-03-07 15:31 UTC, saattrupdan commented
> I am trying to check that the new commits can run on install, but I realized that calling:
> 
> ```
> cookiecutter -f git@github.com:alexandrainst/alexandra-ml-template
> ```
> 
> This downloads the template from the main branch. @saattrupdan do you know if one can call a specific git branch from cookiecutter? I tried:
> 
> `cookiecutter -f gh:alexandrainst/alexandra-ml-template@docstring_fix`
> 
> `cookiecutter -f git@github.com:alexandrainst/alexandra-ml-template@docstring_fix`
> 
> `cookiecutter -f gh:alexandrainst/alexandra-ml-template.git@docstring_fix`
> 
> but it doesn't seem to work

It seems like you can specify the branch name with the `--checkout` argument, as [described here](https://cookiecutter.readthedocs.io/en/latest/usage.html#works-directly-with-git-and-hg-mercurial-repos-too):

```
$ cookiecutter -f git@github.com:alexandrainst/alexandra-ml-template --checkout docstring_fix
```

2024-03-12 12:50 UTC, saattrupdan approved these changes
LGTM!

2024-03-12 12:50 UTC, merged